name: Feature branch

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.2'
    - name: Install app dependencies
      run: flutter pub get
    - name: Lint app
      run: flutter analyze
    - name: Test app
      run: flutter test --coverage --concurrency=2 lib/**/*_test.dart
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
