name: Feature branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.2'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test --concurrency=2
